/** Public surface of the custom-map editor data layer (schema, validation, preview). */
export type {
  CustomMap,
  MapLandHex,
  MapPort,
  MapLandArea,
  HexTypeName,
  PortTypeName,
  FacingName,
} from './mapSchema';
export {
  HEX_TYPE_NAMES,
  PORT_TYPE_NAMES,
  FACING_NAMES,
  SUPPORTED_PLAYER_COUNTS,
  DEFAULT_BOARD_HEIGHT,
  DEFAULT_BOARD_WIDTH,
  EDITOR_DEFAULT_BOARD_HEIGHT,
  EDITOR_DEFAULT_BOARD_WIDTH,
  MIN_BOARD_HEIGHT,
  MIN_BOARD_WIDTH,
  MAX_BOARD_HEIGHT,
  MAX_BOARD_WIDTH,
  parseCoord,
  encodeCoord,
  rowOf,
  colOf,
  coordOf,
  parseMapJson,
  fromRaw,
  mapWithInferredLandAreas,
  mapWithCanonicalLandAreas,
  serializeMapJson,
  emptyMap,
} from './mapSchema';
export type { ValidationIssue, Severity } from './validation';
export {
  validate,
  isValid,
  adjacentHexToEdge,
  facingForEdge,
  MAX_ROW,
  MAX_COL,
} from './validation';
export {
  placeHex,
  clearHex,
  setHexDice,
  setHexLandArea,
  placePort,
  placePortAutoFacing,
  placePortNearHex,
  clearNearestPortToHex,
  smartFillPorts,
  clearAllPorts,
  clearPort,
  toggleRobber,
  togglePirate,
  setName,
  setDescription,
  togglePlayerCount,
  setPlayerCounts,
  setShuffle,
  setBoardSize,
  indexOfHexAt,
  indexOfPortAt,
} from './editorActions';
export {
  enumerateHexCells,
  candidatePortEdges,
  candidatePortEdgesWithin,
  edgesAroundHex,
  legalFacingsForEdge,
  boardSizeForMap,
  minimumBoardSizeForMap,
  clampBoardSize,
} from './editorGrid';
export type { GridHexCell, GridEdgeCell, EditorBoardSize } from './editorGrid';
export { SAMPLE_MAP_JSON } from './sampleMapData';
