services:
  jsettlers-web:
    build: .
    image: jsettlers-web:local
    ports:
      - "8080:8080"
      - "8888:8888"
      - "8880:8880"
    environment:
      JS_BOTS: "7"
      JS_MAX_CONNECTIONS: "50"
